import requests
import json
import random
import string

API_URL = "http://localhost:8000/api/v1"

def random_string(length=8):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=length))

def create_provider():
    email = f"provider_{random_string()}@test.com"
    password = "password123"
    full_name = "Test Provider " + random_string(4)
    
    print(f"Creating provider: {email} / {password}")
    
    # 1. Register
    resp = requests.post(f"{API_URL}/auth/register", json={
        "email": email,
        "password": password,
        "full_name": full_name,
        "role": "provider"
    })
    
    if resp.status_code != 200:
        print(f"Failed to register: {resp.text}")
        return None, None

    # 2. Login
    resp = requests.post(f"{API_URL}/auth/login", json={
        "email": email,
        "password": password
    })
    
    if resp.status_code != 200:
        print(f"Failed to login: {resp.text}")
        return None, None
        
    token = resp.json()["access_token"]
    
    # 3. Create Profile
    headers = {"Authorization": f"Bearer {token}"}
    resp = requests.put(f"{API_URL}/providers/me", headers=headers, json={
        "description": "I am a test provider generated by script.",
        "experience_years": 5
    })
    
    if resp.status_code != 200:
        print(f"Failed to create profile: {resp.text}")
    
    return token, headers, email

def create_service(headers):
    print("Creating service...")
    resp = requests.post(f"{API_URL}/services/", headers=headers, json={
        "title": "Test Service " + random_string(4),
        "description": "This is a test service description.",
        "price": 100.0,
        "duration": "1 hour",
        "category": "Tecnología"
    })
    
    if resp.status_code != 200:
        print(f"Failed to create service: {resp.text}")
        return None
    
    service = resp.json()
    print(f"Service created: ID {service['id']}")
    return service

def create_client_and_chat(provider_headers, service):
    print("Creating client and initiating chat...")
    
    # 1. Register Client
    email = f"client_{random_string()}@test.com"
    password = "password123"
    full_name = "Test Client " + random_string(4)
    
    resp = requests.post(f"{API_URL}/auth/register", json={
        "email": email,
        "password": password,
        "full_name": full_name,
        "role": "client"
    })
    
    if resp.status_code != 200:
        print(f"Failed to register client: {resp.text}")
        return

    # 2. Login Client
    resp = requests.post(f"{API_URL}/auth/login", json={
        "email": email,
        "password": password
    })
    
    token = resp.json()["access_token"]
    client_headers = {"Authorization": f"Bearer {token}"}
    
    # 3. Create Conversation
    print(f"Client {email} creating conversation with provider {service['provider_user_id']}")
    resp = requests.post(f"{API_URL}/conversations", headers=client_headers, json={
        "provider_id": service['provider_user_id'],
        "request_id": None
    })
    
    if resp.status_code == 200 or resp.status_code == 201:
        conv = resp.json()
        print(f"Conversation created: ID {conv['id']}")
        
        # 4. Send Message from Client
        print("Sending message from client...")
        resp = requests.post(f"{API_URL}/conversations/messages/send", headers=client_headers, json={
            "conversation_id": conv['id'],
            "content": "Hello, this is a test message from the client!"
        })
        
        if resp.status_code == 201:
            print("Message sent successfully!")
        else:
             print(f"Failed to send message: {resp.text}")

        return conv['id'], email, password
    else:
        print(f"Failed to create conversation: {resp.text}")
        return None, None, None

def main():
    token, headers, provider_email = create_provider()
    if not token:
        return

    service = create_service(headers)
    if not service:
        return

    conv_id, client_email, client_pass = create_client_and_chat(headers, service)
    
    if conv_id:
        with open("test_credentials.txt", "w") as f:
            f.write("--- TEST DATA CREATED ---\n")
            f.write(f"Conversation ID: {conv_id}\n")
            f.write(f"Provider Email: {provider_email}\n") # Need to pass provider_email
            f.write(f"Client Email: {client_email}\n")
            f.write(f"Password: {client_pass}\n")
        
        print("\n--- TEST DATA CREATED ---")
        print(f"Conversation ID: {conv_id}")
        print("Credentials saved to test_credentials.txt")

if __name__ == "__main__":
    main()
