"""Add professional fields and coordinates to provider profile

Revision ID: 875394d3f6c1
Revises: d80db9b489a3
Create Date: 2026-02-22 14:43:22.840923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875394d3f6c1'
down_revision: Union[str, None] = 'd80db9b489a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('provider_profiles', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('provider_profiles', sa.Column('certifications', sa.JSON(), nullable=True))
    op.add_column('provider_profiles', sa.Column('languages', sa.String(), nullable=True))
    op.drop_column('provider_profiles', 'experience_years')
    op.drop_column('provider_profiles', 'availability')
    op.drop_column('provider_profiles', 'location')
    op.drop_column('provider_profiles', 'base_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('base_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('provider_profiles', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider_profiles', sa.Column('availability', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider_profiles', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('provider_profiles', 'languages')
    op.drop_column('provider_profiles', 'certifications')
    op.drop_column('provider_profiles', 'longitude')
    op.drop_column('provider_profiles', 'latitude')
    # ### end Alembic commands ###
