"""Restore missing profile fields accidentally dropped

Revision ID: ba53d66149e7
Revises: 875394d3f6c1
Create Date: 2026-02-22 14:47:55.860165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba53d66149e7'
down_revision: Union[str, None] = '875394d3f6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('base_rate', sa.Float(), nullable=True))
    op.add_column('provider_profiles', sa.Column('experience_years', sa.Integer(), nullable=True))
    op.add_column('provider_profiles', sa.Column('location', sa.String(), nullable=True))
    op.add_column('provider_profiles', sa.Column('availability', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'availability')
    op.drop_column('provider_profiles', 'location')
    op.drop_column('provider_profiles', 'experience_years')
    op.drop_column('provider_profiles', 'base_rate')
    # ### end Alembic commands ###
