"""Add new provider profile fields

Revision ID: d80db9b489a3
Revises: 42fb2f3a838f
Create Date: 2026-02-22 14:23:11.659062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80db9b489a3'
down_revision: Union[str, None] = '42fb2f3a838f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_profiles', sa.Column('specialty', sa.String(), nullable=True))
    op.add_column('provider_profiles', sa.Column('skills', sa.String(), nullable=True))
    op.add_column('provider_profiles', sa.Column('social_links', sa.JSON(), nullable=True))
    op.add_column('provider_profiles', sa.Column('base_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_profiles', 'base_rate')
    op.drop_column('provider_profiles', 'social_links')
    op.drop_column('provider_profiles', 'skills')
    op.drop_column('provider_profiles', 'specialty')
    # ### end Alembic commands ###
